os: osx
language: objective-c

env:
  matrix:
    - PYTHON_VERSION="2.7"
    - PYTHON_VERSION="3.4"

install:
  - echo "Setting up environment..."
  - ./travis.osx.sh

script:
  - "export PYTHON=`which python3`"
  - "./build.sh picosat-960"
  - "if [ ${PYTHON_VERSION} == "2.7" ]; then python setup.py bdist_wheel; done"
  - "if [ ${PYTHON_VERSION} == "3.4" ]; then python3 setup.py bdist_wheel; done"

addons:
  s3_region: "eu-central-1"
  artifacts:
    paths:
      - $(ls dist/* | tr "\n" ":")
