os:
 - osx

env:
  matrix:
    - PYTHON_VERSION="2.7"
    - PYTHON_VERSION="3.4"

install:
  - echo "Setting up environment..."
  - ./travis.sh

script:
  - env
  - python --version
  - ./build.sh picosat-960
