os: osx
language: objective-c
env:
  matrix:
    # Set up python environment
    # Parameters:
    #     $install_type : {macpython|macports|homebrew|system}
    #         Type of Python to install
    #     $version :
    #         macpython : major.minor.micro e.g. "3.4.1"
    #         macports : major.minor e.g. "3.4"
    #         homebrew : major e.g "3"
    #         system : ignored (but required to be not empty)
    #     $venv_dir : {directory_name|not defined}
    #         If defined - make virtualenv in this directory, set python / pip
    #         commands accordingly
    # ARCH ???
    - INSTALL_TYPE=macpython VERSION=2.7.9
    - INSTALL_TYPE=macpython VERSION=3.5.0
    - INSTALL_TYPE=homebrew VERSION=3
    - INSTALL_TYPE=homebrew VERSION=2

install:
  - brew update
  - brew install swig
  - source terryfy/travis_tools.sh
  # Install Python and pip, maybe virtualenv
  - get_python_environment $INSTALL_TYPE $VERSION $VENV
  - ${PIP_CMD} install wheel
  - ${PIP_CMD} install delocate


script:
  - export PYTHON=`which python3`
  - "./build.sh picosat-960"
  - ${PYTHON_EXE} --version
  - ${PYTHON_EXE} setup.py bdist_wheel
  - delocate-listdeps dist/*.whl


deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAJDNB65PKLACZDGYQ
  secret_access_key:
    secure: "W3BeDD92BGLtkAWSwZRTAfG7b34OPzyFKpDLW8lSZjK9rVW75p1KcDmNrj4Qc+vy2nmzxn77sX3mBUb4h9SfrUug4aGFFo7ibO0OjkVoEXMXrXn1G7E2n1J+FsbMz5NbFajzsTrVkPjZeCAHwkhu4bQwzJ935/ivzEHU4q9huPuOttB37+psJeQj+VZbb+KWFjX/QjSYc8Pdm8ua8emiq6TTmpCKC8qJkVjI5EIqlIsLCbQcjjrAHPuiCRv/XulQRga0vcDCLhyPXSCLP49K7umU6uIr+HEPEzxxS1sUlyf01EPyCKx3fy1uOPGcB12oVx7gzb4Y2SIpVesWn29SLdetD21JiXz4KBlwEc6uTQ8pO583ZxNbo1r4/sP/wEz1sMbacSehndQJDGoQK8ERVIFEhBJEZdJJtxbQ0u6G1InuTzj4PICJXkgdcCpGQQ4JRUYx0cqYMZCGv515rq18X8CqGEdoKwRBi2tRo0CPlCXuC49lN9uSYN/Ewj+nSS2Upy8+DBN3XPFeW+CTCMWAkg6iLVRBmbFlLNcE+AxWqIaumH5Fq4H/VJjnaRn7oyUb/bG3Ald8fuK7oh2qoARHJJB7Rni7bXhUAPih3fh7QJz2dorSatgGn9XzfMwPM84uEkuYD5nK56ChqmXFv6TO78hx4pZrAaZA5gvE54lSacY="
  bucket: pysmt-pkgs
  region: eu-central-1
  local-dir: dist/
  on:
    repo: marcogario/pyPicoSAT
